"""
Sends a formatted HTML email with the top-gainer stock report via Gmail SMTP.
Requires env vars: GMAIL_SENDER, GMAIL_APP_PASSWORD.
"""
import json
import os
import smtplib
import datetime
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

DEFAULT_RECIPIENT = "yuanhuan@usc.edu"


def _get_recipients() -> list[str]:
    raw = os.environ.get("EMAIL_RECIPIENTS", DEFAULT_RECIPIENT).strip()
    if raw.startswith("["):
        try:
            recipients = json.loads(raw)
            if isinstance(recipients, list):
                return [email.strip() for email in recipients if isinstance(email, str) and email.strip()]
        except json.JSONDecodeError:
            pass
    return [email.strip() for email in raw.replace(";", ",").split(",") if email.strip()]


def _build_html(
    session_label: str,
    t0_label: str,
    t1_label: str,
    gainers: list[dict],  # {ticker, price_t0, price_t1, pct_change, analysis, news}
    run_date: datetime.date,
) -> str:
    rows_html = ""
    for rank, g in enumerate(gainers, start=1):
        news_links = "".join(
            f'<li><a href="{n.url}" style="color:#1a73e8;">[{n.publisher}] {n.title}</a></li>'
            for n in g["news"]
            if n.url
        ) or "<li>No news links available</li>"
        rows_html += f"""
        <tr style="border-bottom:1px solid #e0e0e0;">
          <td style="padding:12px 8px;font-weight:bold;font-size:18px;color:#555;">#{rank}</td>
          <td style="padding:12px 8px;">
            <span style="font-size:20px;font-weight:bold;color:#1a73e8;">{g['ticker']}</span><br>
            <span style="color:#34a853;font-size:16px;font-weight:bold;">+{g['pct_change']:.2f}%</span><br>
            <span style="font-size:12px;color:#888;">{t0_label}: ${g['price_t0']:.2f} → {t1_label}: ${g['price_t1']:.2f}</span>
          </td>
          <td style="padding:12px 8px;max-width:350px;line-height:1.5;color:#333;">{g['analysis']}</td>
          <td style="padding:12px 8px;font-size:12px;">
            <ul style="padding-left:16px;margin:0;">{news_links}</ul>
          </td>
        </tr>
        """

    return f"""<!DOCTYPE html>
<html>
<head><meta charset="utf-8"></head>
<body style="font-family:Arial,sans-serif;background:#f9f9f9;margin:0;padding:24px;">
  <div style="max-width:900px;margin:auto;background:#fff;border-radius:8px;box-shadow:0 2px 8px rgba(0,0,0,0.08);overflow:hidden;">
    <div style="background:#1a73e8;color:#fff;padding:24px 32px;">
      <h1 style="margin:0;font-size:22px;">📈 Stock Movers Report — {session_label}</h1>
      <p style="margin:6px 0 0;opacity:0.85;">{run_date.strftime('%A, %B %-d, %Y')} &nbsp;|&nbsp; Comparing {t0_label} → {t1_label} ET</p>
    </div>
    <div style="padding:24px 32px;">
      <p style="color:#555;margin-top:0;">Top {len(gainers)} US stocks by intraday gain in the last hour, with AI-generated analysis.</p>
      <table style="width:100%;border-collapse:collapse;">
        <thead>
          <tr style="background:#f1f3f4;text-align:left;">
            <th style="padding:10px 8px;color:#555;font-size:13px;">#</th>
            <th style="padding:10px 8px;color:#555;font-size:13px;">TICKER / GAIN</th>
            <th style="padding:10px 8px;color:#555;font-size:13px;">WHY IT'S UP</th>
            <th style="padding:10px 8px;color:#555;font-size:13px;">NEWS SOURCES</th>
          </tr>
        </thead>
        <tbody>{rows_html}</tbody>
      </table>
    </div>
    <div style="background:#f1f3f4;padding:16px 32px;font-size:12px;color:#888;">
      Generated by Stock Notifier · Data: Yahoo Finance · Analysis: Claude AI · Not financial advice.
    </div>
  </div>
</body>
</html>"""


def send_report(
    session_label: str,
    t0_label: str,
    t1_label: str,
    gainers: list[dict],
    run_date: datetime.date | None = None,
    dry_run: bool = False,
) -> None:
    if run_date is None:
        run_date = datetime.date.today()

    html = _build_html(session_label, t0_label, t1_label, gainers, run_date)

    recipients = _get_recipients()
    if dry_run:
        print("\n[emailer] DRY RUN — would send email:")
        print(f"  To:      {', '.join(recipients)}")
        print(f"  Subject: 📈 Stock Movers {session_label} — {run_date}")
        print(f"  Body:    {len(html)} chars of HTML")
        # Save HTML to file for inspection
        out_path = f"/tmp/stock_report_{session_label.replace(' ', '_').lower()}.html"
        with open(out_path, "w") as f:
            f.write(html)
        print(f"  Preview: {out_path}")
        return

    sender = os.environ["GMAIL_SENDER"]
    password = os.environ["GMAIL_APP_PASSWORD"]

    msg = MIMEMultipart("alternative")
    msg["Subject"] = f"📈 Stock Movers {session_label} — {run_date}"
    msg["From"] = sender
    msg["To"] = ", ".join(recipients)
    msg.attach(MIMEText(html, "html"))

    with smtplib.SMTP_SSL("smtp.gmail.com", 465) as smtp:
        smtp.login(sender, password)
        smtp.sendmail(sender, recipients, msg.as_string())

    print(f"[emailer] Email sent to {', '.join(recipients)}.")
